sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "4.0.0"
before_script:
  - npm prune
script:
  - npm run test:coverage
  - codeclimate-test-reporter < coverage/lcov.info
after_success:
  - npm run semantic-release
